### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by snacktavish** [lucasnell/jackalope#10]
Hi,
I am trying to install jackalope using 

    devtools::install_github("lucasnell/jackalope")

but I am getting this error. Any pointers?

```
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
ERROR: absolute paths in ‘libs/Rhtslib.so’ include the temporary installation directory: please report to the package maintainer and use ‘--no-staged-install’
```

R version info is:
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          6.0                         
year           2019                        
month          04                          
day            26                          
svn rev        76424                       
language       R                           
version.string R version 3.6.0 (2019-04-26)
nickname       Planting of a Tree

**Comment by lucasnell** [comment]
You may need to update your version of `Rhtslib` using `BiocManager::install("Rhtslib")`. If that doesn't work, can you post the output of `packageVersion("Rhtslib")`, `.libPaths()`, and `Rhtslib::pkgconfig`?

**Comment by snacktavish** [comment]
Updating BiocManager and Rhtslib did it! Thanks.
